# Lab 9

In [1]:
import xlrd 

#### 1)

In [12]:
book = xlrd.open_workbook('house_price.xls')
sheet = book.sheet_by_name('price')
num_record = sheet.nrows

price_list = []
bathroom_list = []
type_list = []
lot_list = []
year_list = []
area_list = []

for i in range(num_record):
    row = sheet.row_values(i)
    price, bathroom, house_type, lot_size, year, area = row
    if i != 0:
        #print(price, bathroom, house_type, lot_size, year, area)
        price_list.append(price)
        bathroom_list.append(bathroom)
        type_list.append(house_type)
        lot_list.append(lot_size)
        year_list.append(year)
        area_list.append(area)
        
print(price_list)
print(bathroom_list)
print(type_list)
print(lot_size)
print(year_list)
print(area_list)

[159900.0, 1100000.0, 182000.0, 169900.0, 148500.0, 444900.0, 178000.0, 209000.0, 349900.0, 1100000.0, 239000.0, 149900.0, 294900.0, 625000.0, 309900.0, 179900.0, 339900.0, 134900.0, 359000.0, 529900.0, 149900.0, 394000.0, 229900.0, 439000.0, 146900.0, 174900.0, 445000.0, 659000.0, 429000.0, 429000.0]
[1.0, 1.0, 2.0, 1.0, 1.0, 6.0, 2.0, 2.0, 2.0, 2.0, 3.0, 2.0, 2.0, 6.0, 3.0, 2.0, 3.0, 2.0, 4.0, 5.0, 3.0, 2.0, 2.0, 4.0, 3.0, 3.0, 4.0, 4.0, 5.0, 4.0]
[' single-family home', ' single-family home', ' condo', ' single-family home', ' single-family home', ' single-family home', ' single-family home', ' single-family home', ' single-family home', ' single-family home', ' single-family home', ' single-family home', ' single-family home', ' single-family home', ' single-family home', ' single-family home', ' single-family home', ' townhouse', ' single-family home', ' single-family home', ' townhouse', ' single-family home', ' single-family home', ' single-family home', ' condo', ' single-famil

#### 2)

In [13]:
import numpy as np

In [16]:
print('The mean of {} is {}'.format('price', np.mean(price_list)))
print('The median of {} is {}'.format('price', np.median(price_list)))
print('The standard deviation of {} is {}'.format('price', np.std(price_list)))

The mean of price is 356700.0
The median of price is 302400.0
The standard deviation of price is 245840.21233313315


#### 3)

In [33]:
print(np.corrcoef(price_list, bathroom_list)) 
print(np.corrcoef(price_list, lot_list)) #strongest correlation
print(np.corrcoef(price_list, year_list)) 
print(np.corrcoef(price_list, area_list)) 

print('The corr between price and bathrooms is {}'\
    .format(np.corrcoef(price_list, bathroom_list)[0][1]))

print('The price and lot size has the strongest correlation with {}'\
     .format(np.corrcoef(price_list, lot_list)[0][1]))

print('The corr between price and year is {}'\
    .format(np.corrcoef(price_list, year_list)[0][1]))

print('The corr between price and area is {}'\
    .format(np.corrcoef(price_list, area_list)[0][1]))

[[1.         0.22789992]
 [0.22789992 1.        ]]
[[1.         0.81068692]
 [0.81068692 1.        ]]
[[ 1.         -0.03834654]
 [-0.03834654  1.        ]]
[[1.         0.40755141]
 [0.40755141 1.        ]]
The corr between price and bathrooms is 0.2278999173038209
The price and lot size has the strongest correlation with 0.8106869237150935
The corr between price and year is -0.038346537078653466
The corr between price and area is 0.407551408717802


#### 4)

In [31]:
from scipy import stats

In [40]:
result = stats.linregress(area_list, price_list)
result2 = stats.linregress(year_list, price_list)
result3 = stats.linregress(bathroom_list, price_list)

print(result.pvalue)
print(result.slope)
print(result.intercept)
print(result.rvalue*result.rvalue)

print()

print(result2.pvalue)
print(result2.slope)
print(result2.intercept)
print(result2.rvalue*result2.rvalue)

print()

print(result3.pvalue)
print(result3.slope)
print(result3.intercept)
print(result3.rvalue*result3.rvalue)

0.025387094399552994
74.37646603912873
171081.13292168107
0.1660981507478648

0.8405564564153876
-382.3268717298298
1114764.977036849
0.0014704569059245446

0.22580469278106366
40480.85846867748
240654.87238979124
0.05193837230708838


#### 5)

In [41]:
print('The price of a house with 2000 sqft is ${}'\
      .format(result.slope*2000+result.intercept))

The price of house with 2000 sqft is $319834.06499993854


In [42]:
print('The price of a house with 4 bathrooms is ${}'\
      .format(result3.slope*4+result3.intercept))

The price of a house with 4 bathrooms is $402578.3062645012


In [44]:
print('The price of a house built in 2000 is ${}'\
      .format(result2.slope*2000+result2.intercept))

The price of a house built in 2000 is $350111.23357718927
